# ================================================================
# 🔗 Linkspector Configuration
# ================================================================
# Checks Markdown files for broken links
# Documentation: https://github.com/UmbrellaDocs/linkspector
# ================================================================

# Directories to scan
dirs:
  - .

# Use .gitignore rules
useGitIgnore: true

# ================================================================
# 🚫 IGNORE PATTERNS
# ================================================================
# Some sites block automated requests (403 Forbidden)
# These are legitimate sites but reject bot traffic
# ================================================================

ignorePatterns:
  # GNU - blocks automated scrapers
  - pattern: '^https://www\.gnu\.org/.*$'
