name: Test Sury Unlocker Script

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  lint-bash:
    name: 🧹 Lint Bash
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
      - name: Set up shellcheck

        uses: ludeeus/action-shellcheck@master
      - name: Run shellcheck
        run: |
          find . -name "*.sh" -print0 | xargs -0 shellcheck # Finds all files with the .sh extension in the current directory and subdirectories

  lint-markdown:
    name: 🧹 Lint Markdown
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Lint Markdown files
        uses: DavidAnson/markdownlint-cli2-action@main
        with:
          globs: "**/*.md" # Checks all Markdown files in the repository
          fix: true # automatically fixes simple problems
          config: ".markdownlint.jsonc" # if you have a configuration file
  #        continue-on-error: true  # to prevent the build from crashing due to errors in the documentation

  secrets-scan:
    name: 🔑 Secrets Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: 0 # Required for diff scan

      - name: TruffleHog Secrets Scan (full)
        if: github.event_name != 'pull_request'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --results=verified,unknown

      - name: TruffleHog Secrets Scan (diff)
        if: github.event_name == 'pull_request'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.pull_request.base.sha }}
          head: ${{ github.event.pull_request.head.sha }}
          extra_args: --results=verified,unknown
